function [Psi, Phi] = WILibFuncs(K, y, u, pf, qf)
    % Parameters
    pe = 206.2; cv = 11.95; pnom = 244.6;
    
    % Library function for different degree of sparsity K
    switch K
        % K = 0
        case 0
            % Vector functions
            Phi{1} = [pf; u(1) * 1e-2; u(1) * qf * 1e-2; qf^2 * 1e-2];
            Phi{2} = [y(1); qf; 1; u(2) * 1e-2; ...
                u(2) * (qf - y(3)) * 1e-2; (qf - y(3))^2 * 1e-2];
            Phi{3} = [u(3) * sqrt((max(y(1) - pe, 0)) * 1e2)];
            
            % Array function
            Psi = [Phi{1}' zeros(1,7); zeros(1,4) Phi{2}' 0; ...
                zeros(1,10) Phi{3}'];
        % K = 1
        case 1
            % Vector functions
            Phi{1} = [pf; u(1) * 1e-2; u(1) * qf * 1e-2; qf^2 * 1e-2; ...
                u(3); y(1); y(2); y(3)];
            Phi{2} = [y(1); qf; 1; u(2) * 1e-2; ...
                u(2) * (qf - y(3)) * 1e-2; (qf - y(3))^2 * 1e-2; ...
                y(1); y(2); y(3); u(1); u(3); pf];
            Phi{3} = [u(3) * sqrt((max(y(1) - pe, 0)) * 1e2); 1];

            % Array function
            Psi = [Phi{1}' zeros(1,14); zeros(1,8) Phi{2}' 0 0; ...
                zeros(1,20) Phi{3}'];
        % K = 2
        case 2
            % Vector functions
            Phi{1} = [pf; u(1) * 1e-2; u(1) * qf * 1e-2; qf^2 * 1e-2; ...
                u(3); y(1); y(2); y(3); sin(u(3)); sin(y(1)); sin(y(2)); ...
                sin(y(3))];
            Phi{2} = [y(1); qf; 1; u(2) * 1e-2; ...
                u(2) * (qf - y(3)) * 1e-2; (qf - y(3))^2 * 1e-2; ...
                y(1); y(2); y(3); u(1); u(3); pf; sin(y(1)); sin(y(2)); ...
                sin(y(3)); sin(u(1)); sin(u(3)); sin(pf)];
            Phi{3} = [u(3) * sqrt((max(y(1) - pe, 0)) * 1e2); 1; sin(1)];

            % Array function
            Psi = [Phi{1}' zeros(1,21); zeros(1,12) Phi{2}' 0 0 0; ...
                zeros(1,30) Phi{3}'];
        % K = 3
        case 3
            % Vector functions
            Phi{1} = [pf; u(1) * 1e-2; u(1) * qf * 1e-2; qf^2 * 1e-2; ...
                u(3); y(1); y(2); y(3); sin(u(3)); sin(y(1)); sin(y(2)); ...
                sin(y(3)); cos(u(3)); cos(y(1)); cos(y(2)); cos(y(3))];
            Phi{2} = [y(1); qf; 1; u(2) * 1e-2; ...
                u(2) * (qf - y(3)) * 1e-2; (qf - y(3))^2 * 1e-2; ...
                y(1); y(2); y(3); u(1); u(3); pf; sin(y(1)); sin(y(2)); ...
                sin(y(3)); sin(u(1)); sin(u(3)); sin(pf); cos(y(1)); ...
                cos(y(2)); cos(y(3)); cos(u(1)); cos(u(3)); cos(pf)];
            Phi{3} = [u(3) * sqrt((max(y(1) - pe, 0)) * 1e2); 1; ...
                sin(1); cos(1)];

            % Array function
            Psi = [Phi{1}' zeros(1,28); zeros(1,16) Phi{2}' 0 0 0 0; ...
                zeros(1,40) Phi{3}'];
end